### PR TITLE
Implemented 'Show Now Playing program' (EPG) functionality

### PR DESCRIPTION
**Pull request by gdomenici**
Hi,

Thanks for the very good plugin -- I use it daily. I did this patch for my own use, but if you find it generally useful, do feel free to pull it. I wanted to be able to show the "now playing" program along with the channel name, in a similar way as you see on zattoo.com itself, i.e. a sort of EPG (Electronic Program Guide).

The way I did it is that I added a new Boolean setting labeled "Show 'now playing' program next to channel name". By default it is False, and when this is the case, the addon behaves exactly as you coded it.

If, on the other hand, one sets it to True, then when looking at the channels list in LiveTV mode you see something like

ITV 1 London - UEFA Champions League Highlights (next: ITV News)
ITV 2 - Release the Hounds (next: The Vampire Diaries)
ITV3 - Law & Order UK (next: Cold Blood)
etc...

In this mode, the channel cache is a separate file, and it will last 4 minutes as opposed to 1 full day, because of course you want to have fresh program information.

I have tested the addon in both modes -- with the new setting off and on, and it seems to behave properly. Again, feel free to pull if you feel it's a change worthy of submitting to the main Kodi plugin repo.

(For what it's worth, and to establish a bit of credibility, I am the author of another Kodi video plugin, https://github.com/gdomenici/plugin.video.pcloud-video-streaming).

Kind regards,

Guido

### CODE REVIEW

**Comment by nancpasc** [comment]
Hi,

Sorry for the late reply, and thank you for you contribution ! I'll have quick look asap.

Regards.

P.

**Comment by nancpasc** [comment]
Haven't tried yet but the changeset looks fine, so I accepted the pull request as is. I'll give you a feedback in the next few days :)

Thanks a lot !

P.

**Comment by gdomenici** [comment]
Thanks for the pull P.

In the meantime I've been dogfooding your plugin with my changes for the
last week or so, and everything seems to be pretty stable. Let me know if
any issues.

Kind regards,

Guido

**Comment by rainman74** [comment]
Hallo,

da die Live-TV-Streams ja alle nicht mehr zuverlässig funktionieren, habe ich mir ein Zattoo-Abo zugelegt. Leider ist die Zattoo-eigene App auf FireTV zu träge und daher nutze ich auch das Plugin Zattoo-Box mit der EPG-Erweiterung von gdomenici. Ich habe damit den Menü-Eintrag "TV" ersetzt.

Nun würde ich aber gerne das PVR-Plugin IPTV Simple Client in einen "Plugin Simple Client" umschreiben, mit dem die Zattoo-Streams direkt vom Plugin geliefert werden können. Dazu kann man in Kodi für die Steuerung der Zattoo-Box entsprechene Command-Lines verwenden.

Die M3U-Datei würde dann beispielhaft so aussehen:
‪#‎EXTM3U‬
‪#‎EXTINF‬:-1 tvg-id="ARD.de" tvg-logo="ard.png",DAS ERSTE
plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=ard
#EXTINF:-1 tvg-id="ZDF.de" tvg-logo="zdf.png",ZDF
plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=zdf
#EXTINF:-1 tvg-id="RTL.de" tvg-logo="rtl.png",RTL
plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=rtl_deutschland

Vorteile für diese Lösung wären:

```
direkte Einbindung von Zattoo und auch weiteren TV-Plugins in das Kodi PVR-Framework
es können alle Kodi-Standard PVR-Masken und Funktionen verwendet werden
externes EPG kann weiter genutzt werden (z.B. Rytec)
```

Da ich nun aber noch keine Entwicklungserfahrung mit Kodi-Plugins habe - für das intensive Einlesen fehlt mir leider die Zeit: Wer kennt sich hier aus - am besten bereits mit dem IPTV Simple Client - und wer kann oder möchte hier mithelfen? Das Plugin würde dann auch hier Open Source zur Verfügung gestellt. Bei Interesse bitte melden.

Es wäre natürlich auch möglich, dass die Idee von nancpasc selbst aufgegriffen wird.

Vg

**Comment by gdomenici** [comment]
Hi Vg,

I get the gist of your message via Google Translate, but if you'd consider rewriting it in English maybe there's a chance I (or perhaps nancpasc) can help.

Best regards,

Guido

**Comment by rainman74** [comment]
Hello there,

since the free Live-TV streams all no longer function reliably, I've gained a Zattoo subscription. Unfortunately Zattoo's own app is too sluggish on FireTV and therefore I use the plugin Zattoo box with the EPG extension of gdomenici. I have therefore replaced the menu item "TV" with the plugin-page "live tv".

Now I would like to rewrite the PVR plugin "Simple IPTV client" into a "PLUGIN Simple client", with that the Zattoo streams can be delivered directly from the plugin to the PVR core.

The M3U file would look like as an example:
#EXTM3U
#EXTINF: -1 TVG id = "ARD.de" TVG logo = "ard.png" the first
plugin: //plugin.video.zattoobox/ ext = LiveTV & mode = watch & id = ard?
#EXTINF: -1 TVG id = "ZDF.de" TVG logo = "zdf.png" ZDF
plugin: //plugin.video.zattoobox/ ext = LiveTV & mode = watch & id = ZDF?
#EXTINF: -1 TVG id = "RTL.de" TVG logo = "rtl.png" RTL
plugin: //plugin.video.zattoobox/ ext = LiveTV & mode = watch & id = rtl_deutschland?

Advantages of this solution are:
- direct integration of Zattoo and other TV/Stream-Plugins in the Kodi PVR framework
- all Kodi standard PVR masks and functions are useable
- external EPG could be used, too (eg Rytec)

But since I do not have any development experience with Kodi plugins yet, - for intensive reading unfortunately I lack the time: Who wants to help here? The plugin would then provided open source.

Of course, it would also be possible that the idea will be taken up by nancpasc or gdomenici itself.

Best regards

**Comment by rainman74** [comment]
Hi Guido,

i've translated it on git. Sorry, I thought Zattoo is only for german
speaking users... :-)

Regards
Kalle

2015-12-17 11:35 GMT+01:00 gdomenici notifications@github.com:

**Comment by rainman74** [comment]
I've searched for a PVR-API Documentation but without success... it seams that only Kodi core developers should write such Plugins.

As a workaround the Zattoo Box plugin possibly could write all Zattoo-Stream-URLs of Zattoos favorites incl. the required URL parameters in a local M3U file every time when Kodi starts or once a day. This in turn could be then included in PVR IPTV Simple Client.

I think this way would be very easy to implement, right?

Later I'll post an example for such a generated file.

**Comment by gdomenici** [comment]
Hi @rainman74 

Sounds like a reasonable idea and indeed it sounds simple to implement, but then again I'll let @nancpasc comment given that he "owns" most of the ZattooBox source code.

Best regards,

Guido

PS: not only German-speaking users on Zattoo... there's lots of Italian and French and British channels. I personally am an Italian native speaker.

**Comment by nancpasc** [comment]
Hi,

I do not plan to change anything in the plugin in the next 3 months or so. So if you guys have ideas to improve the current version, you can submit new pull requests.

However, the best way to extend ZB would be to use the built-in mechanism to write extensions (In the same way as Livetv.py and recordings.py). It will also be easier to credit the contributions :)

When you think everything is ready, let met know so I can submit an update to Kodi Repository.

Regards,
P.

**Comment by nancpasc** [comment]
Thus, I don't really know how the PVR stuff actually works, @rainman74 I guess you know better :)

**Comment by gdomenici** [comment]
In principle it's not too hard. But it can't be done in a Video addon like ZattoBox, because Kodi doesn't let video addons run in the background. For something like you are asking, you'd need a Service addon, which are meant for exactly this kind of background tasks.

So there are two choices:
1. You create a new Service addon, and you duplicate there a substantial part of ZattooBox's code. Or,
2. You create a new Service addon, and you add a dependency on ZattooBox, and call into ZattooBox's routines. This is probably a better option, but I have no experience in cross-addon calls. I just know it ought to be possible.

In either case, this Service addon would poll your Zattoo "favorites" once a day and copy their streaming URLs into the M3U playlist as you suggest.

I can look into developing this Service addon, but I'll need some time coz I still need to figure out the cross-addon dependency thing. If in the meantime @rainman74 would like to provide me an example of what the M3U should look like, I can use that as a target. Also, where in the Kodi virtual filesystem should this playlist end up?

Best regards,

Guido

**Comment by rainman74** [comment]
Hi Guido and nancpasc,

first thank you for your feedback!

If it's OK for nancpasc to use his code, I suggest the following implementation for such a Service Plugin to provide a M3U for KODI PVR Simple IPTV client.

For developing an own PVR-Client there is too litte API documentation available. And such a client also needs to be coded in C++ an then complied as a shared library for each OS. Too much work! :-)


----- Service Plugin e.g. titled "Zattoo M3U Generator" -----

1. Definitions

1.1 Zattoo related
ZattooChannel-ID: eg. "rtl_deutschland"
ZattooChannel-Title: eg. "RTL Deutschland"

1.2 XMLTV EPG related (eg. for Rytec EPG Downloader)
tvg-id: eg. "RTL.de"
tvg-logo: eg. "RTL.png"
tvg-name: eg. "[COLOR deepskyblue]RTL[/COLOR]"
group-title: eg. "German-TV-Channels"

2. ZattooBox Service-Plugin

2.1 Description
Zattoo M3U Generator Service Plugin is a standalone plugin which contains code from ZattooBox Video-Plugin, eg. ZAPISESSION (if that is ok for nancpasc!)
I would not recommend to cross-call another plugin, because ZattooBox Video-Plugin is required to be installed then and that is not necessary because nobody will use KODI PVR for viewing TV and a video plugin at the same time.

2.2 Configurable Plugin Settings (settings.xml)
GenerateTime = Frequency for writing M3U File (every xx minutes for background task to generate file new) (nancpasc: do you know how long Zattoo SIDs are valid and what a proper value for that would be?)
Maxrate = maximal allowed bitrate for stream (perhaps for a next release? actually hard coded to "5000" is ok)
Minrate = minimal allowed bitrate for stream (perhaps for a next release? actually hard coded to "600" is ok)

2.2.1 Suggestion for settings.xml
<settings>
    <setting id="zattooPassword" value="..." />
    <setting id="zattooUsername" value="..." />
    <setting id="m3uPath" value="/storage/emulated/0/zattoo.m3u" />
    <setting id="m3uPathType" value="0" />
    <setting id="m3uGenerateTime" value="60" />

	--- for a next release ---
	<setting id="zattooMaxrate" value="..." />)
	<setting id="zattooMinrate" value="..." />)
</settings>


2.3 Separate Properties File (mapping.xml) - this file must be edited manually in notepad
Mapping table for ZattooChannel-ID + tvg-id + tvg-logo + group-title + tvg-name

2.3.1 Suggestion for mapping.xml
<mappings>
    <mapping>
        <id>0</id>
        <zattoo-id>rtl_deutschland</zattoo-id>
		<tvg-id>RTL.de</tvg-id>
		<tvg-logo>rtl.png</tvg-logo>
		<tvg-name>[COLOR deepskyblue]RTL[/COLOR]</tvg-name>
		<group-title>TV-Channels</group-title>
    </mapping>
    <mapping>
        <id>1</id>
        <zattoo-id>HD_ard</zattoo-id>
		<tvg-id>ARD.de</tvg-id>
		<tvg-logo>ardhd.png</tvg-logo>
		<tvg-name>[COLOR skyblue]Das Erste[/COLOR]</tvg-name>
		<group-title>TV-Channels</group-title>
    </mapping>
	...
</mappings>


3. Process
Every xx Minutes (m3uGenerateTime) the backround task start to generate the M3U File (first deletes the file and then writes it, perhaps the file could also be updated instead of firstly being deleted)

Step 1: Write M3U Header (#EXTM3U)
Step 2: Iterate over all Zattoo-favorites and for each favorite (zattoo-id) write the following two lines in M3U File (for params use mapping.xml and settings.xml)

Line 1: #EXTINF:-1 tvg-id="<tvg-id>" tvg-logo="<tvg-logo>" group-title="<group-title>",<tvg-name>
Line 2: the stream-url with the appropriate url-params, eg.	http://zathlslive-a.akamaihd.net/xxx-live.m3u8?maxrate=5000&sig=xxx&uuid=xxx&initialrate=0&tsid=xxx&minrate=600&channel=xxx&csid=xxx

If a mapping definition for a zattoo-id is not found in mapping.xml, the channel is ignored and will not be written to M3U.


4. Example for a generated M3U File with one favorite channel

--- zattoo.m3u ---
#EXTM3U
#EXTINF:-1 tvg-id="ARD.de" tvg-logo="ardhd.png" group-title="TV Group",[COLOR deepskyblue]DAS ERSTE[/COLOR]
http://zathlslive-a.akamaihd.net/HD_ard-live.m3u8?maxrate=5000&sig=45345345345345345345&uuid=53555-c555-67567-b34535-43583235fe&initialrate=0&tsid=45662354364646b4&minrate=600&channel=HiQ_ard&csid=a35353535358724234
--- zattoo.m3u ---

**Comment by rainman74** [comment]
Hi Guido and nancpasc,

first thank you for your feedback!

If it's OK for nancpasc to use his code, I suggest the following implementation for such a Service Plugin to provide a M3U-File for KODI PVR Simple IPTV client.

For developing a new PVR-Client there is too little API documentation available, because such a client needs to be coded in C++ and then compiled as a shared library for each OS. Too much work! :-)

----- Service Plugin e.g. titled "Zattoo M3U Generator" -----

1 Definitions

1.1 Zattoo related

```
ZattooChannel-ID: eg. "rtl_deutschland"
ZattooChannel-Title: eg. "RTL Deutschland"
```

1.2 XMLTV EPG related (eg. for Rytec EPG Downloader)

```
tvg-id: eg. "RTL.de"
tvg-logo: eg. "RTL.png"
tvg-name: eg. "[COLOR deepskyblue]RTL[/COLOR]"
group-title: eg. "German-TV-Channels"
```

2 ZattooBox code based Service-Plugin

2.1 Description
Zattoo M3U Generator Service Plugin is a standalone plugin which contains code from ZattooBox Video-Plugin, eg. ZAPISESSION (if that is ok for nancpasc!)
I would not recommend to cross-call another plugin, because ZattooBox Video-Plugin is required to be installed then and that is not necessary because I think nobody will use KODI PVR for viewing TV and a video plugin at the same time for same task. :-)

2.2 Configurable Plugin Settings (settings.xml)
GenerateTime = Frequency for writing M3U File (every xx minutes for background task to generate file new) (nancpasc: do you know how long Zattoo SIDs are valid and what a proper value for that would be?)
Maxrate = maximal allowed bitrate for stream (perhaps for a next release? actually hard coded to "5000" is ok)
Minrate = minimal allowed bitrate for stream (perhaps for a next release? actually hard coded to "600" is ok)

2.2.1 Suggestion for settings.xml

```
    <settings>
        <setting id="zattooPassword" value="..." />
        <setting id="zattooUsername" value="..." />
        <setting id="m3uPath" value="/storage/emulated/0/zattoo.m3u" />
        <setting id="m3uPathType" value="0" />
        <setting id="m3uGenerateTime" value="60" />

        --- for a next release ---
        <setting id="zattooMaxrate" value="..." />)
        <setting id="zattooMinrate" value="..." />)
    </settings>
```

2.3 Separate Properties File (mapping.xml) - this file must be edited manually in notepad
Mapping table for ZattooChannel-ID + tvg-id + tvg-logo + group-title + tvg-name

2.3.1 Suggestion for mapping.xml

```
    <mappings>
        <mapping>
            <id>0</id>
            <zattoo-id>rtl_deutschland</zattoo-id>
            <tvg-id>RTL.de</tvg-id>
            <tvg-logo>rtl.png</tvg-logo>
            <tvg-name>[COLOR deepskyblue]RTL[/COLOR]</tvg-name>
            <group-title>German-TV-Channels</group-title>
        </mapping>
        <mapping>
            <id>1</id>
            <zattoo-id>HD_ard</zattoo-id>
            <tvg-id>ARD.de</tvg-id>
            <tvg-logo>ardhd.png</tvg-logo>
            <tvg-name>[COLOR skyblue]Das Erste[/COLOR]</tvg-name>
            <group-title>German-TV-Channels</group-title>
        </mapping>
        ...
    </mappings>
```

3 Processing
Every xx Minutes (m3uGenerateTime) the backround task start to generate the M3U File (first deletes the file and then writes it, perhaps the file could also be updated instead of firstly being deleted)

Step 1: Write M3U Header

```
#EXTM3U
```

Step 2: Iterate over all Zattoo-favorites and for each favorite (zattoo-id) write the following two lines in M3U File (for params use mapping.xml and settings.xml)

```
Line 1: #EXTINF:-1 tvg-id="<tvg-id>" tvg-logo="<tvg-logo>" group-title="<group-title>",<tvg-name>
Line 2: the stream-url with the appropriate url-params, eg. http://zathlslive-a.akamaihd.net/xxx-live.m3u8?maxrate=5000&sig=xxx&uuid=xxx&initialrate=0&tsid=xxx&minrate=600&channel=xxx&csid=xxx
```

If a mapping definition for a zattoo-id is not found in mapping.xml, the channel is ignored and will not be written to M3U.

4 Example for a generated M3U File with one favorite channel

```
--- zattoo.m3u ---
#EXTM3U
#EXTINF:-1 tvg-id="ARD.de" tvg-logo="ardhd.png" group-title=German-TV-Channels",[COLOR deepskyblue]DAS ERSTE[/COLOR]
http://zathlslive-a.akamaihd.net/HD_ard-live.m3u8?maxrate=5000&sig=45345345345345345345&uuid=53555-c555-67567-b34535-43583235fe&initialrate=0&tsid=45662354364646b4&minrate=600&channel=HiQ_ard&csid=a35353535358724234
--- zattoo.m3u ---
```

**Comment by gdomenici** [comment]
Hi @rainman74 

Thanks for the detailed spec. I'll look into it in the next few days, but first I wanna make sure @nancpasc is OK with having chunks of his code reused elsewhere.

Guido

**Comment by nancpasc** [comment]
Hi,

Yes you can reuse the actual code and fork as necessary.

However if you need something to be changed in the main repository, please submit a pull request.

Regards,

P.

**Comment by rainman74** [comment]
Hi nancpasc,

thank you for permissiven to reuse your code. I think a fork would be the way to go, Guido?

But please reply once again to following question:
Do you know how long a Zattoo SID is valid and can be used before a new one needs to be generated?

Regards
Kalle

**Comment by nancpasc** [comment]
Hi, 

I don't know how long it is valid, but a good practice is to update the SID each time you call the API. this process is fully implemented in ZapiSession.py

P.

**Comment by rainman74** [comment]
We would call the api only every xx minutes to generate the M3U file. Then we have to try it out, how long SID is valid. I assume it lasts for 2 hours, that would be my suggestion. But I try it later, if Guido is willing to start with the Plugin.

@Guido: I've only limited time, but I could support you with fixing bugs directly in code and testing.

**Comment by gdomenici** [comment]
There's a working code skeleton now in the pvr-connect branch of my fork (https://github.com/gdomenici/ZattooBox/tree/pvr-connect). It's massively hacky but it does generate the M3U on startup, with the correct URLs (but still using most;y hardcoded values in the EXTINF). I still occasionally get '401 unauthorized' when I play those channels using the PVR Simple IPTV client, so I guess there's still some token validity issues (suggestions welcome @nancpasc ). Should not be a big deal to sort out at any rate. Will keep hammering on it in the next few days.

Guido

**Comment by rainman74** [comment]
I checked your testbuild. Great work!

But I assume there is a sort of security mechanism from zattoo, because you only can use 2 channels at a time. If you only switch between the same 2 channels (l've tried that for over 10 times), everything is fine. But if you switch to a 3rd channel, the autorization tokens of ALL channels gets invalidated.

I've no idea at the moment to deal with that, but I assume that it is not possible for a service plugin to supply PVR Client new stream-urls with all new autorization tokens &sig, &tsid, &csid in realtime at channel switching :-(

I'm afraid that only a dedicated PVR Zattoo Client could to that and not a plugin...

**Comment by gdomenici** [comment]
Thanks for the testing @rainman74 . Your observation "I assume that it is not possible for a service plugin to supply PVR Client new stream-urls with all new autorization tokens &sig, &tsid, &csid in realtime at channel switching" gave me an idea, which I tried and alas did not work.

The idea is that the generated M3U would contain URLs looking like this:

```
#EXTINF: ...
plugin://plugin.video.zattoobox/?ext=PvrSync&cid=itv-1-london&mode=watch&id=itv-1-london
```

i.e. it uses the exact same URI format that the _original_ ZattooBox plugin attaches (behind the scenes) to each of its own GUI list items. Normally the Kodi core code knows to invoke the correct plugin when it encounters a URI starting with "plugin://".

But unfortunately the PVR SImple IPTV client does not understand those URIs. I was hoping it would invoke the original ZattooBox plugin (which in turn would correctly insert the right &sig et cetera), but it just says "XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.zattoobox/?ext=PvrSync&cid=itv-1-london&mode=watch&id=itv-1-london".

I start to think you're right that "only a dedicated [C++] PVR Zattoo Client could to that and not a plugin"...  I'll mull a few more ideas, but I doubt we can go much further down this road.

**Comment by gdomenici** [comment]
At any rate, I committed the changes to a sub-sub branch https://github.com/gdomenici/ZattooBox/tree/pvr-connect-uri-test if you wanna give it a spin anyway. The delta with the one you tried is that now the playlist entries now start with plugin://...

**Comment by rainman74** [comment]
Hi Guido,

that's a great step ahead! Then we only need PVR SImple IPTV now to accept such URLs
"plugin://plugin.video.zattoobox/?ext=PvrSync&cid=itv-1-london&mode=watch&id=itv-1-london".

Does anybody know nightik, the author of PVR SImple IPTV Client?

We could contact him and ask, if he can support in suppling the protocol "plugin" also as "http".

Best regards
Kalle

**Comment by gdomenici** [comment]
Good idea. I don't know nightik, but I created this issue in their bugtracking system: https://github.com/kodi-pvr/pvr.iptvsimple/issues/51. Let's see what they say.

Best regards,

Guido

**Comment by gdomenici** [comment]
Looks like we've hit a dead-end. afedchin from the Simple IPTV PVR plugin said, tersely,

> It's not possible.

If there are no other ideas, I suggest we abandon this route.

Guido

**Comment by rainman74** [comment]
Hi all,

yes, I've read it. But afedchin didn't say if it is impossible for actual Client version (that we already knew) or because of how PVR API works?

Anyway, perhaps we could improve this MOD of ZattooBox:
https://drive.google.com/file/d/0B2Acxd6qjdZnYXBnYWpuak1VWm8/view

It is already very promising and only a few things missing/are buggy:
- bug less direct channel switching in EPG (in actual version 0.89 switching to a channel starts to loop all channels, strange...)
- scrolling in EPG is kind of buggy, at the end of channels it should'nt beginn at the top at pressing button button again - kind of irritating
- Vorschau/Preview is useless and should be removed
- update EPG also if using/open it as a direct favorite in KODI (<favourite name="EPG">PlayMedia(&quot;plugin://plugin.video.zattooboxExt/?mode=epg&quot;)</favourite>)

What do you guys think in making a next version of ZattooBox 2.0 with a new and improved EPG of using ZattooBoxExt code? :-)

Best Regards and have a nice Christmas!
Kalle

**Comment by rainman74** [comment]
BTW Guido, do you know where the problem is here?

Open ZattoBox via favorites works well with this URL and ShowNowPlaying and ShowNextPlaying is up to date:
<favourite name="Zattoo TV" >ActivateWindow(10025,&quot;plugin://plugin.video.zattoobox/&quot;,return)</favourite> -> then click "Live TV - favorites"

But if I use this favorite for direct call the favorites page, the ShowNowPlaying and ShowNextPlaying seam to not get updated and shown info is outdated:
<favourite name="TV">ActivateWindow(10025,&quot;plugin://plugin.video.zattoobox/?cat=fav&amp;ext=LiveTV&amp;mode=root&quot;,return)</favourite>

**Comment by nancpasc** [comment]
@rainman74, I do like your idea, EPG is something i wanted to integrate but I did not find the time to do it. I didn't check the mod you mentionned yet, but I will.

Someone sent me something similar a few months ago, with the EPG stored in a SQLLite Db. I found that neat but I wasn't able to get in touch with the author. I could post it somewhere, it might be a good starting point.

Regards,
P.

**Comment by rainman74** [comment]
Storing EPG data in a SQLLite DB needs much work for updating and deleting the entries.
I would rather assume to use Zattoos online EPG in realtime and only cache it in RAM as long as EPG-Page is opened. There's not so much data for an EPG of one day for all of own Zattoos favories.

To use Zattoos EPG data, Guido and also the author of ZattooBoxExt start with a very promising approach.

I provide a few pictures of how Zattoos own EPG page and ZattooBoxExt EPG is presented.

I think for EPG Page the following functions are needed first:
- timeline of all channels (list) with last, actual and upcoming shows of actual day (show in a 24h time scale) (as in ZattooBoxExt, but scrolling till the end of the day is in the MOD not very fluid)
- indicator of actual time (as in ZattooBoxExt)
- direct channel switching (it's buggy in ZattooBoxExt)

Next steps would be:
- show show details in an popup window (or in a frame as in ZattooBoxExt)
- show picture of show (as in ZattooBoxExt)
- time selector to skip to selected show time
- day selector to skip to selected day and show the shows of that day

What do you think? :-)

ZattooBoxExt EPG page:
zattooboxext
https://drive.google.com/file/d/0B2Acxd6qjdZnYXBnYWpuak1VWm8/view

ZattooBox official EPG page:
zattoo
zattoo2
zattoo3
zattoo4

**Comment by nancpasc** [comment]
In fact, I just realized the extension you mentioned is the same as the one I got from Daniel.

I'm pretty sure it's the best way to go.

Regards.

P.

**Comment by gdomenici** [comment]
I checked it out, it's an impressive piece of work, despite the (relatively harmless) bugs. I would be in favor of merging it into the ZattooBox codebase. Now, I don't shy away from interesting chunks of work, but this looks like it would be safer in @nancpasc 's capable hands.

Anyway, just for fun I tried merging (locally) ZattooBoxExt into ZattooBox's current HEAD. While there were obviously several merge conflicts, they were pretty easy to resolve "naively". The resulting tree was a valid plugin that worked just like ZattooBoxExt. But as I said before, I'd trust the merge result much more if it was done by nancpasc.

Wanna take a shot P?

**Comment by nancpasc** [comment]
Hi,

I suggest the following : I create a new branch "1.x contrib" in which I'll merge all pull requests. As I don't have much time in the next few days, I'll just make, if necessary, a bit of cleanup before merging everything in main branch ZattooBox 2.0.

Remember, the less in the core, the better. If most of the code can be put in an external .py it will be much easier to credit and maintain.

Regards !

P.

**Comment by gdomenici** [comment]
Sounds good to me. Thanks nancpasc.

**Pull request merged**
