### PR TITLE
Upgrade add-on to Python 3

### PR DESCRIPTION
**Pull request by claudep**
This is a first-pass, untested port to Python 3.

### CODE REVIEW

**Review by nancpasc — APPROVED** [review]
Thank you for your contribution !

**Comment by claudep** [comment]
Thanks for merging. As I said in a comment above, I didn't test it for real. Hopefully you did! In any case, just tell me if I broke anything and I'll try to help.

**Comment by nancpasc** [comment]
Hi Claude,

Thank you very much for the contribution. I did merge it after a quick look, it seemed fine.
However, I dit not test it so far. In fact, I'm not sure I gonna push it in the Kodi 19 repository.

There is a Zattoo PVR Client plugin which offers way more options than this one, it's surely the way to go : https://kodi.tv/addon/pvr-client/zattoo-pvr-client

With best regards.

**Comment by claudep** [comment]
Thanks for the pointer. But tell me, can the Zattoo PVR Client run over just a normal Internet connection? I wasn't able to set it up (extension activated, username/pw configured, but nothing more).

**Comment by flabb17** [comment]
Yes the Zatoo PVR addon works "standalone". Only internet and User/password request.
Not easy to understand, but result visible on "live tv" section ! 
Tutorial requested.
Realy nice addon , but thanks nancpasc for zattoobox and all the past years with your solution.

**Comment by claudep** [comment]
Oh, I noticed the Zattoo PVR suffers from the exact same bug: https://github.com/rbuehlma/pvr.zattoo/commit/73b3111b5. But as it's C++, it's a lot more annoying to fix until the next version is published :-/

**Comment by nancpasc** [comment]
I guess all the zattoo plugins did suffer from the last service update. However, It should be emphasized that they put effort to keep these 3rd party addons alive.

I've tried the latest update of the PVR client from the official repository, and it's working for me.

**Comment by nancpasc** [comment]
forgot to mention that the ZattooBox plugin has also been updated yesterday

**Pull request merged**
